name: Java CI/CD With ACR
on:
  push:
    branches: [ "master"]
    pull_request:    # Checks *before* merge
      branches: [ "master" ]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run tests
        run: mvn -B test --file pom.xml

      # build and push to ACR
    build-and-push:
      needs: test # only runs if test passed
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

          # login to ACR
        - name: Login to Azure Container Registry
          run: |
            echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_LOGIN_SERVER }} \
              -u ${{ secrets.ACR_USERNAME }} --password-stdin

          # build and tag the images
        - name: Build docker Image
          run: |
            docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/my-java-app:${{ github.sha }} .
            docker tag ${{ secrets.ACR_LOGIN_SERVER }}/my-java-app:${{ github.sha }} ${{ secrets.ACR_LOGIN_SERVER 
            }}/my-java-app:latest

          # push to ACR
        - name: Push to ACR
          run: |
            docker push ${{ secrets.ACR_LOGIN_SERVER }}/my-java-app:${{ github.sha }}
            docker push ${{ secrets.ACR_LOGIN_SERVER }}/my-java-app:latest

